# https://aka.ms/yaml

trigger:
  - master

variables:
  dockerRegistryServiceConnection: container-registry-thezanzibarcompany
  containerRegistry: thezanzibarcompany.azurecr.io

resources:
  containers:
    - container: jdk8
      image: thezanzibarcompany.azurecr.io/ubi-jdk8
      endpoint: container-registry-thezanzibarcompany

stages:
  - stage: Build
    displayName: 'Build & Unit Test Stage'
    jobs:
      - job: Build
        displayName: 'Compile sources and run unit tests'
        pool:
          vmImage: 'ubuntu-latest'
        container: jdk8
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'sbt test package'
              failOnStderr: true
              noProfile: false
              noRc: false
      - job: Publish
        displayName: 'Compile sources, assemble and publish package'
        pool:
          vmImage: 'ubuntu-latest'
        container: jdk8
        steps:
          - task: DownloadSecureFile@1
            name: publishKey
            inputs:
              secureFile: 'publish.asc'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                gpg --keyserver keyserver.ubuntu.com --recv FB4EF913C8E9D815
                gpg --import --import-options keep-ownertrust $(publishKey.secureFilePath)
                echo "addSbtPlugin(\"io.crashbox\" % \"sbt-gpg\" % \"latest.release\")" > project/sbtgpg.sbt
              failOnStderr: true
              noProfile: false
              noRc: false
          - task: DownloadSecureFile@1
            name: sbtCredentials
            inputs:
              secureFile: 'internal_repo_credentials.sbt'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                cp $(sbtCredentials.secureFilePath) ./
                sbt publish
              failOnStderr: true
              noProfile: false
              noRc: false
